!function(a,b){"undefined"!=typeof module?module.exports=b():"function"==typeof define&&"object"==typeof define.amd?define(b):this[a]=b()}("domready",function(a){function b(a){for(h=1;a=c.shift();)a()}var c=[],d,e=document,f=e.documentElement,g=f.doScroll,h=(g?/^loaded|^c/:/^loaded|c/).test(e.readyState);e.addEventListener&&e.addEventListener("DOMContentLoaded",d=function(){e.removeEventListener("DOMContentLoaded",d,!1);b()},!1);g&&e.attachEvent("onreadystatechange",d=function(){/^c/.test(e.readyState)&&
(e.detachEvent("onreadystatechange",d),b())});return a=g?function(b){self!=top?h?b():c.push(b):function(){try{f.doScroll("left")}catch(c){return setTimeout(function(){a(b)},50)}b()}()}:function(a){h?a():c.push(a)}});
var cookiesPolicy={settings:{cookiename:"cookiePolicy",layerid:"cookies-policy",landingid:"cookies-landing",layerwidth:"990px"},createFragment:function(a){var b=document.createDocumentFragment(),c=document.createElement("div");for(c.innerHTML=a;c.firstChild;)b.appendChild(c.firstChild);return b},addToBody:function(a){a=cookiesPolicy.createFragment(a);document.body.insertBefore(a,document.body.childNodes[0])},addToHead:function(a){a=cookiesPolicy.createFragment(a);document.head.insertBefore(a,document.head.childNodes[0])},
getTopDomain:function(){var a,b,c=document.location.hostname.split(".");for(a=c.length-1;0<=a;a--)if(b=c.slice(a).join("."),document.cookie="weird_get_top_level_domain=cookie;domain=."+b+";",-1<document.cookie.indexOf("weird_get_top_level_domain=cookie"))return document.cookie="weird_get_top_level_domain=;domain=."+b+";expires=Thu, 01 Jan 1970 00:00:01 GMT;",b;return""},addEvent:function(a,b,c){a.attachEvent?a.attachEvent&&a.attachEvent("on"+b,c):a.addEventListener(b,c,!1)},removeEvent:function(a,
b,c){a.detachEvent?a.detachEvent&&a.detachEvent("on"+b,c):a.removeEventListener(b,c,!1)},areCookiesEnabled:function(){var a=!!navigator.cookieEnabled;"undefined"!=typeof navigator.cookieEnabled||a||(document.cookie="testcookie",a=-1!=document.cookie.indexOf("testcookie"));return a},createCookie:function(){cookiesPolicy.setCookie(!0)},removeCookie:function(){cookiesPolicy.setCookie(!1)},setCookie:function(a){var b=cookiesPolicy.getTopDomain(),c=cookiesPolicy.settings.cookiename;1==a?(a=new Date,a.setTime(a.getTime()+
864E9)):a="Thu, 01 Jan 1970 00:00:01 GMT";document.cookie=c+"=1;expires="+a.toUTCString()+"; path=/; domain="+b},getCookie:function(){var a=cookiesPolicy.settings.cookiename,b;return 0<document.cookie.length&&(b=document.cookie.indexOf(a+"="),-1!=b)?(b=b+a.length+1,c_end=document.cookie.indexOf(";",b),-1==c_end&&(c_end=document.cookie.length),unescape(document.cookie.substring(b,c_end))):""},checkPolicy:function(){return cookiesPolicy.areCookiesEnabled()?(1!=cookiesPolicy.getCookie()&&cookiesPolicy.showLayer(),
!0):!1},showLayer:function(){var a='<div id="%%LAYERID%%"> <div class="info_cookies">  <a href="#" title="Aceptar y cerrar" class="close2" onclick="cookiesPolicy.hideLayer(); return false;">X</a><span>Utilizamos cookies propias y de terceros. Al navegar est&aacute;s aceptando nuestra <a title="Ver pol&iacute;tica de cookies de Vandal" rel="nofollow" href="http://www.vandal.net/cgi-bin/pagina.pl?pag=cookies" target="_blank" id="'+
cookiesPolicy.settings.landingid+'">pol&iacute;tica de cookies</a>.</span> </div></div>';cookiesPolicy.addToHead(('<style type="text/css">#%%LAYERID%% {width: 100%; background-color: #dfe8ee; box-shadow: 0 -3px 10px #999; position: fixed; bottom: 0; z-index: 999999;}#%%LAYERID%% .info_cookies {position: relative; width: 100%; max-width: '+cookiesPolicy.settings.layerwidth+"; margin: 0 auto; background-color: #c7ced3; font-size: 12px; line-height: 15px; font-family: Arial, Helvetica, sans-serif;}#%%LAYERID%% .info_cookies span {padding: 6px; display: inline-block;}#%%LAYERID%% .info_cookies a {color: #002e48; font-weight: bold;}#%%LAYERID%% .info_cookies .close2 {position: absolute; top: 6px; right: 10px; color: #000; font-weight: bold; font-size: 20px; text-decoration: none;}</style>").replace(/%%LAYERID%%/g,
cookiesPolicy.settings.layerid));cookiesPolicy.addToBody(a.replace(/%%LAYERID%%/g,cookiesPolicy.settings.layerid));cookiesPolicy.attachEvents()},hideLayer:function(a){a||(a=window.event);if(("click"==a.type||"mousedown"==a.type)&&(a.target||a.srcElement).id==cookiesPolicy.settings.landingid)return!1;"undefined"!=typeof document.getElementById(cookiesPolicy.settings.layerid)&&document.body.removeChild(document.getElementById(cookiesPolicy.settings.layerid));cookiesPolicy.removeEvents();cookiesPolicy.createCookie()},
removeEvents:function(){cookiesPolicy.removeEvent(document,"mousedown",cookiesPolicy.hideLayer);cookiesPolicy.removeEvent(document,"click",cookiesPolicy.hideLayer)},attachEvents:function(){cookiesPolicy.addEvent(document,"mousedown",cookiesPolicy.hideLayer);cookiesPolicy.addEvent(document,"click",cookiesPolicy.hideLayer)}};domready(function(){cookiesPolicy.checkPolicy()});
