var mono={version:"1.5.1.0"};mono.CFG={};mono.CFG.IS_DEVEL=(window.location.host.indexOf("stage1")!==-1);mono.CFG.IS_EXTERNAL=(window.location.host.indexOf("www")==-1);mono.CFG.IS_BLOGS=(window.location.host.indexOf("blogs")!==-1);if(mono.CFG.IS_EXTERNAL&&mono.CFG.IS_DEVEL){mono.CFG.URL_MONO="http://www.stage1.monografias.com/"}else{if(mono.CFG.IS_EXTERNAL&&!mono.CFG.IS_DEVEL){mono.CFG.URL_MONO="http://www.monografias.com/"}else{mono.CFG.URL_MONO="/"}}
mono.CFG.DEBUG=true&&mono.CFG.IS_DEVEL;mono.CFG.URL_BASE="/";mono.CFG.URL_LOGIN=mono.CFG.URL_MONO+"usuario/login";mono.CFG.URL_LOGOUT=mono.CFG.URL_MONO+"usuario/logout";mono.CFG.URL_REGISTRO=mono.CFG.URL_MONO+"usuario/registro";mono.CFG.URL_RANDOM="//static.monografias.com/random/";mono.CFG.URL_JAVASCRIPT=mono.CFG.URL_RANDOM+"js/";mono.CFG.FACEBOOK_APP_ID=168580619833974;mono.CFG.URL_FACEBOOK=mono.CFG.URL_MONO+"usuario/conectarFacebook";mono.CFG.URL_FACEBOOK2=mono.CFG.URL_MONO+"usuario/vincularFacebook";mono.CFG.COMENTARIOS_MAX_CAPS=70;mono.MSG_TYPE={ADVERTENCIA:"advert",INFORMACION:"informacion",ERROR:"error",STOP:"stop",PROCESANDO:"procesando"};mono.msg={ERROR_500:"Ha ocurrido un error en el servidor. Por favor, vuelva a intentar en unos minutos.",ERROR_403_COMENTARIO:"Para dejar un comentario debe iniciar sesi&oacute;n.",ERROR_403_DENUNCIA:"Para denunciar un comentario, debe iniciar sesion.",ERROR_403_VOTAR:"Para poder votar, debe iniciar sesion.",ERROR_400_COMENTARIO:"Antes de enviar, escriba el comentario.",ERROR_AUTENTICACION:"El usuario y la contrase&ntilde;a no coinciden.",ERROR_SERVIDOR:"Ocurri&oacute; un error en Monografias.com. Por favor, espere unos instantes e intente nuevamente.",ERROR_FALTA_EMAIL:"Falta escribir el e-mail.",ERROR_FALTA_PASS:"Falta escribir la contrase&ntilde;a.",PLEASE_WAIT:"Aguarde un instante por favor...",CONFIRMA_DENUNCIA:"Confirme por favor que este comentario viola los Terminos y Condiciones de Monografias.com",DENUNCIA_ENVIADA:"&nbsp;|&nbsp; <strong>Comentario denunciado</strong>",NO_VOTAR_DOBLE:"No puede votar el mismo comentario dos veces",CTRL_D_FAVORITO:"Presione Aceptar y luego CTRL + D para agregar esta pagina a sus favoritos.",REGISTRESE:"&iexcl;Reg&iacute;strese!",INICIAR_SESION:"Iniciar sesi&oacute;n",SALIR:"Salir"};mono.util={getCookie:function(b){var a=document.cookie.match("(^|;) ?"+b+"=([^;]*)(;|$)");if(a){return(unescape(a[2]))}else{return null}},setCookie:function(e,c,b){var a=e+"="+escape(c)+"; path=/";if(b){var d=new Date();d.setDate(d.getDate()+365);a+="; expires="+d.toGMTString()+"; path=/"}
document.cookie=a},deleteCookie:function(b){var a=new Date();a.setDate(a.getDate()-1);console.log(a.toGMTString());document.cookie=b+="=; expires="+a.toGMTString()+"; path=/"},sanearTexto:function(a){var d=a.match(/[A-Z]/g);if(d){var c=d.length;var b=a.length;if(((c/b)*100)>mono.CFG.COMENTARIOS_MAX_CAPS){a=a.charAt(0).toUpperCase()+a.substr(1).toLowerCase()}}
a=a.replace(/([A-Za-z0-9,\.!\?\$\-])\1{5,}/g,"$1$1$1$1");return a},createMsg:function(c,b,a){var d={};d.cerrar=a?a.cerrar:false;d.dismiss=a?a.dismiss:false;$texto=$("<p/>");$texto.html(c);$msg=$("<div/>");$msg.addClass("mensaje-de").addClass(b);if(d.cerrar){$msg.addClass("con-cerrar")}
if(d.dismiss){$msg.addClass("con-dismiss")}
$msg.html($texto);return($msg)},agregarFavorito:function(){var titulo=document.title;var url=parent.location.href;if(url=="http://www.monografias.com/"){titulo="Monografias.com";}
if(document.all){window.external.AddFavorite(url,titulo);}else if(window.sidebar){window.sidebar.addPanel(titulo,url,"");}else{alert(mono.msg.CTRL_D_FAVORITO);}},base64encode:function(c){_keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";var a="";var k,h,f,j,g,e,d;var b=0;while(b<c.length){k=c.charCodeAt(b++);h=c.charCodeAt(b++);f=c.charCodeAt(b++);j=k>>2;g=((k&3)<<4)|(h>>4);e=((h&15)<<2)|(f>>6);d=f&63;if(isNaN(h)){e=d=64}else{if(isNaN(f)){d=64}}
a=a+_keyStr.charAt(j)+_keyStr.charAt(g)+_keyStr.charAt(e)+_keyStr.charAt(d)}
return a},evalResultData:function(texto){var rx=(texto.replace(/\r|\n|\r\n|\t/g,""));try{var r=eval("("+rx+")");return(r)}catch(ex){return false}},registroRedirect:function(){mono.console.log("Se llamo a la funcion obsoleta registro()");window.location=mono.CFG.URL_REGISTRO},popup:function(a){cuteLittleWindow=window.open(a,"littleWindow","location=no,width=390,height=470,scrollbars=yes")},registro:function(a){cuteLittleWindow=window.open(a,"littleWindow","location=no,width=415,height=475,scrollbars=yes")}};mono.ui={activarAjaxLogin:function(){$.fn.colorbox.settings.bgOpacity=0.6;$.fn.colorbox.settings.transition="elastic";$("#js-login").colorbox({contentWidth:"500px",contentHeight:"210px",contentInline:"#login-box-container .login-box",afterShowCallback:function(){var a=$("#js-loginform","#colorbox");var c=$(".login-box .notificacion","#colorbox");try{activarTwitter()}catch(b){}
a.submit(function(i){i.preventDefault();c.html(mono.util.createMsg(mono.msg.PLEASE_WAIT,mono.MSG_TYPE.PROCESANDO));a.desactivar();var d="";var f=$(":input[name='email']",a).val();var h=$(":input[name='password']",a).val();var g=$(":input[name='recordar']",a).attr("checked")?1:0;if(!f){d+=mono.msg.ERROR_FALTA_EMAIL}
if(!h){d+=" "+mono.msg.ERROR_FALTA_PASS}
if(d){c.html(mono.util.createMsg(d,mono.MSG_TYPE.ERROR));c.show();a.activar();return false}else{if(mono.CFG.IS_EXTERNAL){var j=mono.CFG.URL_LOGIN+"?email="+f+"&password="+mono.util.base64encode(h)+"&recordar="+g+"&jsoncallback=?";$.getJSON(j,function(e){mono.ui.handleLoginResult(e)})}else{$.ajax({url:mono.CFG.URL_LOGIN,type:"POST",data:a.serialize(),success:function(e){mono.ui.handleLoginResult(mono.util.evalResultData(e))},error:function(k,l,e){mono.console.log(k,l,e);switch(k.status){case 401:c.html(mono.util.createMsg(mono.msg.ERROR_AUTENTICACION,mono.MSG_TYPE.ERROR));c.show();a.activar();break;default:c.html(mono.util.createMsg(mono.msg.ERROR_SERVIDOR,mono.MSG_TYPE.ERROR));c.show();a.activar();break}}})}}})}});if(mono.CFG.IS_BLOGS){$(".js-login-blogs").click(function(a){a.preventDefault();$("#js-login").trigger("click")})}
if(mono.temp_mono_id){$("#js-inicia-primero a:eq(1)").click(function(a){a.preventDefault();$("#js-login").trigger("click")})}},handleLoginResult:function(b){mono.console.dir(b);var a=$("#js-loginform","#colorbox");var c=$(".login-box .notificacion","#colorbox");if(b.result){location.reload()}else{c.html(mono.util.createMsg(mono.msg.ERROR_AUTENTICACION,mono.MSG_TYPE.ERROR));c.show();a.activar()}},invitarAmigoAjax:function(){$.fn.colorbox.settings.bgOpacity=0.6;$.fn.colorbox.settings.transition="elastic";$("#js-invitar-amigo").colorbox({contentWidth:"400px",contentHeight:"400px",contentIframe:mono.CFG.URL_BASE+"cgi-bin2/recomendar.pl"})}};mono.setHandlers=function(){if(mono.TEMP.usuario){var a=$('<span class="secundario"><span class="sprites-2011 sprite-log-user">&nbsp;<a href="'+mono.CFG.URL_MONO+'usuario/perfilprivado">'+mono.TEMP.usuario.firstname+(mono.TEMP.usuario.lastname?" "+(mono.TEMP.usuario.lastname.length>20?mono.TEMP.usuario.lastname.split(" ")[0]:mono.TEMP.usuario.lastname):"")+'</a></span>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="'+mono.CFG.URL_MONO+'usuario/logout" id="botonSalir">'+mono.msg.SALIR+"</a></span>");$("#Idioma").html(a)}else{var a=$('<span class="secundario"><span class="sprites-2011 sprite-log-user">&nbsp;<a href="'+mono.CFG.URL_MONO+'usuario/registro">'+mono.msg.REGISTRESE+'</a></span>&nbsp;&nbsp;|&nbsp;&nbsp;<a id="js-login" href="'+mono.CFG.URL_MONO+'usuario/login">'+mono.msg.INICIAR_SESION+"</a></span>");$("#Idioma").html(a);if($("#login-box-container").length){setTimeout(mono.ui.activarAjaxLogin,500)}}
if(jQuery.fn.colorbox){mono.ui.invitarAmigoAjax()}else{$.getScript(mono.CFG.URL_JAVASCRIPT+"jquery.colorbox.js",function(){setTimeout(mono.ui.invitarAmigoAjax,500)})}
$("#Navegacion li:last-child a").addClass("ultima");mono.console.log("mono.setHandlers listo.")};mono.init=function(){if(jQuery.browser.msie&&jQuery.browser.version=="6.0"){var a=document.getElementsByTagName("head")[0];var b=document.createElement("link");b.type="text/css";b.rel="stylesheet";b.href=mono.CFG.URL_RANDOM+"mono_v2-ie6.css";b.media="screen";a.appendChild(b)}
if(mono.CFG.DEBUG){if((!("console"in window)||!("firebug"in console))){mono.console={log:function(){var e=Array.prototype.slice.call(arguments);var f=e.join(" | ");$("#mono_debug_console").show().find(".inner").append("<p>"+f+"</p>")},info:function(){},warn:function(){},error:function(){},assert:function(){},dir:function(){},dirxml:function(){},group:function(){},groupEnd:function(){},time:function(){},timeEnd:function(){},count:function(){},trace:function(){},profile:function(){},profileEnd:function(){}};$(document).ready(function(){var e=$('<div id="mono_debug_console" style="display:none;"><div style="display:none" class="inner clearfix"></div><span class="show_hide">Consola</span></div>');$("body").append(e);$("#mono_debug_console .show_hide").bind("click",function(f){$("#mono_debug_console").toggleClass("abierto").find(".inner").toggle()})})}else{mono.console=console}}else{var d=["log","debug","info","warn","error","assert","dir","dirxml","group","groupEnd","time","timeEnd","count","trace","profile","profileEnd"];mono.console={};for(var c=0;c<d.length;++c){mono.console[d[c]]=function(){}}}
mono.TEMP=mono.TEMP||{};if(mono.util.getCookie("monoauth_session_hash")){mono.TEMP.usuario={};mono.TEMP.usuario.firstname=mono.util.getCookie("monoauth_firstname")||"";mono.TEMP.usuario.lastname=mono.util.getCookie("monoauth_lastname")||"";mono.TEMP.usuario.username=mono.util.getCookie("monoauth_username")||""}
jQuery.fn.extend({desactivar:function(){$(':input[readonly!="readonly"]:not(.desactivado)',this).each(function(){var e=$(this);e.attr("readonly","readonly").addClass("desactivado js-dis");if(e.hasClass("submit")){e.addClass("busy");e.attr("disabled","disabled").attr("oldValue",$.trim($(this).html()));e.html("Enviando...");e.blur()}});return this},activar:function(){return $(".desactivado.js-dis",this).each(function(){$(this).removeAttr("readonly").removeClass("desactivado js-dis");if($(this).attr("oldValue")){$(this).removeClass("busy");$(this).html($(this).attr("oldValue"));$(this).removeAttr("disabled").removeAttr("oldValue")}})}});mono.console.log("mono.init listo.")};mono.init();$(document).bind("ready",function(){mono.setHandlers();});favorito=mono.util.agregarFavorito;favoritohome=mono.util.agregarFavorito;popup=mono.util.popup;registro=mono.util.registroRedirect;function verificarradio(c){var d=c.opt&&c.opt.selectedIndex;var a=c.opt&&c.opt[d]&&c.opt[d].value;var b=c.query.value;switch(a){case"aex":ventanita=window.open("/cgi-bin2/search_mod.cgi?query="+b+"&opt="+a,"Asksearch","location=no,width=780,height=500,scrollbars=yes,status=yes,menubar=yes,resizable=yes");break;case"org":b=escape(b);window.location=("/cgi-bin/search.cgi?query="+b);break;case"ain":window.location=("/cgi-bin2/search_mod.cgi?query="+b+"&opt="+a);break;default:b=escape(b);window.location=("/cgi-bin/search.cgi?query="+b);break}
return false}
function KeyPressEnterK(){if(window.event.keyCode==13){window.event.keyCode=0;verificarradio()}}
function checkKeyPressed(b,c){b=(b)?b:(window.event)?event:null;if(b){var a=(b.charCode)?b.charCode:((b.keyCode)?b.keyCode:((b.which)?b.which:0));if(a==13){verificarradio(c);return false}}}
function recargarPantalla(){window.location=mono.CFG.URL_FACEBOOK}
function recargarPantalla2(){window.location=mono.CFG.URL_FACEBOOK2};
var monoTrabajoCat = 1;